# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-07-23 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'History',
                'db_table': 'history',
                'ordering': ('time_created',),
            },
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.IntegerField()),
                ('level', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Post',
                'db_table': 'post',
                'ordering': ('time_created',),
            },
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('content', models.TextField(blank=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connaisaV0.history')),
            ],
            options={
                'verbose_name_plural': 'Review',
                'db_table': 'review',
                'ordering': ('time_created',),
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('pw', models.CharField(max_length=20)),
                ('secure_qa', models.CharField(max_length=53)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('number', models.CharField(blank=True, max_length=15)),
                ('photo', models.ImageField(blank=True, upload_to='user_photo')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'User',
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connaisaV0.user'),
        ),
        migrations.AddField(
            model_name='history',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='connaisaV0.post'),
        ),
    ]
