# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-07-23 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connaisaV0', '0004_auto_20180723_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='student_id',
            new_name='student',
        ),
    ]
