# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-07-23 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connaisaV0', '0005_auto_20180723_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='student',
        ),
        migrations.AddField(
            model_name='history',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='connaisaV0.user'),
        ),
    ]
