# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-07-23 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connaisaV0', '0006_auto_20180723_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
